### PR TITLE
howto/unicode.po

### PR DESCRIPTION
**Pull request by Seluj78**

### CODE REVIEW

**Comment by PyDocTeur** [comment]
Rajoutez moi un automerge et ca pars en prod !

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: approved_testok)
</details>

**Comment by Seluj78** [comment]
Plouf

**Comment by Seluj78** [comment]
Plouf plouf

**Comment by Seluj78** [comment]
Plouf plouf plouf

**Comment by Seluj78** [comment]
Plouf plouf plouf plouf

**Comment by Seluj78** [comment]
Plouf plouf plouf plouf plouf

**Comment by Seluj78** [comment]
Rhoo

**Comment by Seluj78** [comment]
TADA ?

**Comment by PyDocTeur** [comment]
Il me faut une review et un AUTOMERGE et c'est fini !

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: testok)
</details>

**Comment by PyDocTeur** [comment]
C'est noté, celle là, je n'y touche pas.

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: donotmerge)
</details>

**Comment by PyDocTeur** [comment]
Yay ! Quelqu'un pour review ?

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: testok)
</details>

**Comment by PyDocTeur** [comment]
Y'a-il un humain dans le coin pour review ?

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge_testok)
</details>

**Comment by PyDocTeur** [comment]
DONOTMERGE ou automerge ? Je sais pas quoi faire la ! cc @

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge_testok_donotmerge)
</details>

**Comment by PyDocTeur** [comment]
Y'a-il un humain dans le coin pour review ?

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge_testok)
</details>

**Comment by PyDocTeur** [comment]
DONOTMERGE ou automerge ? Je sais pas quoi faire la ! cc @JulienPalard, @Seluj78

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge_testok_donotmerge)
</details>

**Comment by PyDocTeur** [comment]
Schizophrène, schizophrène, tu vas trop vite ! (label DONOTMERGE et automerge en même temps #lol)

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge_donotmerge)
</details>

**Comment by PyDocTeur** [comment]
Y'a-il un humain dans le coin pour review ?

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge_testok)
</details>

**Review by PyDocTeur — APPROVED** [review]

**Comment by Seluj78** [comment]
Bump after approval because events from the bot are ignored

**Comment by PyDocTeur** [comment]
Attention @Seluj78 @PyDocTeur, la PR va être mergée !

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge_approved_testok)
</details>

**Comment by Seluj78** [comment]
Retrying after changing cmmit message to empty string

**Comment by PyDocTeur** [comment]
Attention @Seluj78 @PyDocTeur, la PR va être mergée !

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge_approved_testok)
</details>

**Comment by PyDocTeur** [comment]
Merci @Seluj78 @PyDocTeur, c'est merge !

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge_approved_testok)
</details>

**Pull request merged**
