### PR TITLE
corrige fautes dans CONTRIBUTING.rst

### PR DESCRIPTION
**Pull request by Seluj78**

### CODE REVIEW

**Comment by PyDocTeur** [comment]
Les tests passent \o/ Bravo et merci @Seluj78 ! Est-ce qu'un relecteur peut me relire ça ? CC @JulienPalard, @Seluj78 (et j'ai rien contre un petit label `automerge`)

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: testok)
</details>

**Comment by PyDocTeur** [comment]
Je mergerai cette PR dès que les tests passeront et qu'elle sera approuvée.

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge)
</details>

**Review by JulienPalard — APPROVED** [review]

**Comment by PyDocTeur** [comment]
Dès que les tests passent, je merge ! Merci @Seluj78 @JulienPalard !

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge_approved)
</details>

**Comment by Seluj78** [comment]
up ?

**Comment by Seluj78** [comment]
Ping ?

**Comment by Seluj78** [comment]
up !

**Pull request closed without merging**
