### PR TITLE
Fix #972 sur les doubles espaces dans contributingContributing doubles espaces

### PR DESCRIPTION
**Pull request by Seluj78**

### CODE REVIEW

**Review by PyDocTeur — APPROVED** [review]

**Comment by PyDocTeur** [comment]
Test

**Comment by PyDocTeur** [comment]
DONOTMERGE ou automerge ? Je sais pas quoi faire la

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
DONOTMERGE ou automerge ? Je sais pas quoi faire la

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
Décidez vous les gars, DONOTMERGE ou automerge ?

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
Décidez vous les gars, DONOTMERGE ou automerge ?

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
DONOTMERGE ou automerge ? Je sais pas quoi faire la

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by Seluj78** [comment]
Hmm

**Comment by PyDocTeur** [comment]
Décidez vous les gars, DONOTMERGE ou automerge ?

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
Décidez vous les gars, DONOTMERGE ou automerge ?

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
Schizophrène, schizophrène, tu vas trop vite ! (label DONOTMERGE et automerge en même temps #lol)

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
Schizophrène, schizophrène, tu vas trop vite ! (label DONOTMERGE et automerge en même temps #lol)

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
DONOTMERGE ou automerge ? Je sais pas quoi faire la

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
Décidez vous les gars, DONOTMERGE ou automerge ?

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
DONOTMERGE ou automerge ? Je sais pas quoi faire la

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
Décidez vous les gars, DONOTMERGE ou automerge ?

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
Schizophrène, schizophrène, tu vas trop vite ! (label DONOTMERGE et automerge en même temps #lol)

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
Décidez vous les gars, DONOTMERGE ou automerge ?

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
DONOTMERGE ou automerge ? Je sais pas quoi faire la

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
Schizophrène, schizophrène, tu vas trop vite ! (label DONOTMERGE et automerge en même temps #lol)

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by PyDocTeur** [comment]
Schizophrène, schizophrène, tu vas trop vite ! (label DONOTMERGE et automerge en même temps #lol)

---
<details>
  <summary>Disclaimer</summary>
  
I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by Seluj78** [comment]
Waou

**Comment by Seluj78** [comment]
Test

**Comment by Seluj78** [comment]
lol

**Comment by Seluj78** [comment]
La ca marche

**Comment by Seluj78** [comment]
Why ?

**Comment by Seluj78** [comment]
Ping

**Comment by PyDocTeur** [comment]
Décidez vous ! On approve et on DONOTMERGE !? @PyDocTeur

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

</details>

**Comment by Seluj78** [comment]
Ping

**Comment by PyDocTeur** [comment]
Décidez vous ! On approve et on DONOTMERGE !? @PyDocTeur

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: approved_donotmerge)
</details>

**Comment by Seluj78** [comment]
Meme msg, pas de changement

**Comment by Seluj78** [comment]
Fix du bug, pas de changement d estate

**Comment by PyDocTeur** [comment]
Si la CI passe, on merge ! Merci @Seluj78 pour la PR et @PyDocTeur pour les reviews !

---
<details>
  <summary>Disclaimer</summary>

I'm a bot made by the [Translation and AFPy teams](https://github.com/AFPy/PyDocTeur/graphs/contributors) on their free
time. I might say or do dumb things sometimes. Don't blame me, blame the developer !

[Source code](https://github.com/afpy/pydocteur)

(state: automerge_approved)
</details>

**Pull request closed without merging**
